#!/bin/bash

hostname=srv-lin1-01
domain=lin1.local
dnsip=10.10.10.11
ip=10.10.10.11
mask=255.255.255.0
gateway=10.10.10.2
subnet=10.10.10.0
rangemin=10.10.10.110
rangemax=10.10.10.119

dc1=lin1
dc2=local

domain=$dc1.$dc2

# Initial install
chmod +x ../linInit
../linInit $hostname $domain $dnsip $mask $gateway
# Install and configure DHCP server
chmod +x ./dhcp
./dhcp $subnet $mask $rangemin $rangemax $domain $ip $gateway
# Install and configure DNS server
chmod +x ./dns
./dns $domain $ip
# Install and configure ldap server


# restart
reboot